name: PhpStan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Test PhpStan level 8
        run: |
          cd project/
          vendor/bin/phpstan analyse src --memory-limit=-1
